### ISSUE TITLE
Extract files as MSG binaries

### ISSUE THREAD

**Issue by markb-trustifi** [HiraokaHyperTools/pst-extractor#1]
Is it possible to extract files from PST archive in a binary form? I believe they should be MSG files. Is it correct?
If it does, what about parsing these files with https://github.com/HiraokaHyperTools/msgreader library? 
What would be the difference in the performance and results quality?

**Comment by kenjiuno** [comment]
PST is a big database file.
So, it is not true that: MSG files are directly stored inside PST.

PST to MSG process requires to add a _logical writing layer_ on msgreader side, which currently it doesn't exist.

![pst-msg-layers](https://github.com/HiraokaHyperTools/pst-extractor/assets/5955540/76fd9c52-f559-48a8-b3cf-a0c370cf956c)

Also this requires knowledge of both packages _pst-extractor_ and _msgreader_. So it should be implemented on independent package like _pst_to_msg_.

**Comment by kenjiuno** [comment]
The early alpha version is available: [@hiraokahypertools/pst_to_msg - npm](https://www.npmjs.com/package/@hiraokahypertools/pst_to_msg)

**Comment by kenjiuno** [comment]
This demo [pst-extractor-demo](https://hiraokahypertools.github.io/pst-extractor-demo/) now includes the msg exporter:

<img width="609" height="576" alt="Image" src="https://github.com/user-attachments/assets/086b846c-508f-48f9-abd2-a60eea016ffe" />
