### ISSUE TITLE
Error: property type 0x1002 is unknown. please define a typeConverter in PropertyValueResolverV1.ts

### ISSUE THREAD

**Issue by markb-trustifi** [HiraokaHyperTools/pst-extractor#2]
Please export `typeConverters` or add it as a member of class `PropertyValueResolverV1`.
It will allow adding to it custom type handlers and avoid errors like:
```
getPropertyContext.list() resolving property key=0x1204 type=0x1002 of subNode of nodeId=2181284,nidType=4 failure --> 
Error: property type 0x1002 is unknown. please define a typeConverter in PropertyValueResolverV1.ts
at Object.<anonymous> (/app/node_modules/@hiraokahypertools/pst-extractor/dist/PropertyContextUtil.js:64:35)
at Generator.throw (<anonymous>)
at rejected (/app/node_modules/@hiraokahypertools/pst-extractor/dist/PropertyContextUtil.js:6:65)
```

**Comment by kenjiuno** [comment]
Hi
The error is fixed upon the latest version `@hiraokahypertools/pst-extractor@0.1.0-alpha.8`
But I don't have the pst having 0x1002 (`PT_MV_SHORT`)
Please try it.

**Comment by kenjiuno** [comment]
The updated version `@hiraokahypertools/pst-extractor@0.1.0-alpha.11` will be able to bring type converter.

- https://hiraokahypertools.github.io/pst-extractor/typedoc/interfaces/PSTOpts.html#provideTypeConverterOf

**Comment by kenjiuno** [comment]
`@hiraokahypertools/pst-extractor@0.1.0-alpha.12` has `provideFallbackTypeConverterOf`.
This is helpful to ignore errors about unknown typeConverters.

- https://hiraokahypertools.github.io/pst-extractor/typedoc/interfaces/PSTOpts.html#provideFallbackTypeConverterOf
